### ISSUE TITLE
SAMM Practitioner guidance and vetting

### ISSUE THREAD

**Issue by maximbaele** [owaspsamm/samm-suite#1]
* How to submit data
* How to anonymize data*
*  How practitioners are vetted
*  Data stewardship (both for the benchmark team and the practitioners)

**Comment by aramhovsepyan** [comment]
Isn't this a duplicate issue (#17 and #18)

**Comment by johnellingsworth** [comment]
assigned to @maximbaele to review

**Comment by maximbaele** [comment]
This is certainly related, but is specific for the role of the practitioner in the benchmark project. 

* How to submit data
* How to anonymize data
* How practitioners are vetted
* Data stewardship (both for the benchmark team and the practitioners)

**Comment by johnellingsworth** [comment]
Housekeeping. Closing issues that have been marked as 'Done'
