### ISSUE TITLE
NIST SSDF Mapping

### ISSUE THREAD

**Issue by johnellingsworth** [owaspsamm/samm-suite#10]
**Goals**

- Leverage SAMM’s capabilities to create a roadmap towards SSDF compliance
- Starting point for further mapping initiatives

**Comment by johnellingsworth** [comment]
**Goals**

- Leverage SAMM’s capabilities to create a roadmap towards SSDF compliance
- Starting point for further mapping initiatives

- [ ] Generate first draft of NIST mapping
- [ ] Follow up with NIST on process
- [ ] Apply recommendations from NIST to mapping
- [ ] Review with stakeholders for feedback on quality of mapping and update accordingly
- [ ] Share final version with NIST and publish on SAMM website

**Comment by aramhovsepyan** [comment]
I went through it again end-to-end with a fresh head. I now have a mapping that I can rationalize. Let me know when you guys are ready with a sweep and we can sync the results and finalize it.
It seems to me that we should refine the relationship in both directions. So for some mappings SAMM is the generic end while NIST is the specific end as SAMM is much broader.
Anyway - happy to discuss whenever you are ready.

**Comment by johnellingsworth** [comment]
@aramhovsepyan I invited you to a meeting we have scheduled for Tuesday where we can discuss. I also heard back from NIST and the news is good.

**Comment by aramhovsepyan** [comment]
Awesome. I hope I can reply here to thisSent from a smartphoneAram Hovsepyan, ***@***.*** 13 Nov 2022, at 19:28, John Ellingsworth ***@***.***> wrote:﻿
@aramhovsepyan I invited you to a meeting we have scheduled for Tuesday where we can discuss. I also heard back from NIST and the news is good.

**Comment by johnellingsworth** [comment]
Housekeeping. Closing issues that have been marked as 'Done'
