### ISSUE TITLE
Microsoft SDL Mapping

### ISSUE THREAD

**Issue by maximbaele** [owaspsamm/samm-suite#35]
This issue tracks the work to map the Microsoft SDL to SAMM

- [x] Review SDL and come up with a rough-order-of-magnitude effort estimation for the work
- [x] Map SDL to SAMM
- [ ] Publish the mapping and market the work

**Comment by aramhovsepyan** [comment]
I don't think it's worth our time to map to SDL.

**Comment by aramhovsepyan** [comment]
I'm ready with an initial version.
https://docs.google.com/spreadsheets/d/1WiQcn7wFzSM8xg78SqkIM1QF2C48jBCYi_N_6kOq174/edit?gid=449823732#gid=449823732

**Comment by aramhovsepyan** [comment]
Reviewed by Seba. I'm closing this issue.

**Comment by infosecdad** [comment]
Provided comments in the google doc: https://docs.google.com/document/d/1jV4P4tG2XHF-I-M2OPD9vrDy6tA5LaEKDkSjLnIuT1c/edit
