### ISSUE TITLE
Create and deliver SAMM v2.1 presentation at Global AppSec Dublin

### ISSUE THREAD

**Issue by SebaDele** [owaspsamm/samm-suite#38]

**Comment by SebaDele** [comment]
work in progress - https://docs.google.com/presentation/d/1U0kBN-YJkg_qflNuoPzQ52cxV5W-3iUka6G_dpiAXIs/edit#slide=id.g1db3a657542_0_0

**Comment by johnellingsworth** [comment]
Housekeeping. Closing issues that have been marked as 'Done'
