### ISSUE TITLE
OpenCRE links in guidance

### ISSUE THREAD

**Issue by Pat-Duarte** [owaspsamm/samm-suite#41]
We have a request from Rob van der Veer to add links to OpenCRE in our stream guidance section
https://staging.opencre.org/

The suggestion was for us to do something like this
![Image](https://github.com/owaspsamm/samm-suite/assets/41348252/b7e9f0e3-e203-4a30-b286-3e806ba5ec85)

Implementing it would require something like the original version of references, including links through YAML files.

Perhaps something reasonable for this stage would be to add links to the Google Docs through the Google Form for stream guidance. We would need someone to do this. Is there a mapping we can use?

**Comment by Pat-Duarte** [comment]
https://staging.opencre.org/cre/433-442

**Comment by Pat-Duarte** [comment]
We need the mappings in a way that we can add to the spreadsheet.
Rob is doing some of the mappings
We're sending a copy of the spreadsheet to Rob so he can do it.
Ask Rob to create a blog post about this.

**Comment by johnellingsworth** [comment]
Housekeeping. Closing issues that have been marked as 'Done'
